development:
    adapter: postgresql
    database: fbksedlcany-dev
    username: postgres
    password: root
    host: localhost
    encoding: UTF8
    port: 5454

test:
    adapter: postgresql
    database: fbksedlcany-tst
    username: postgres
    password: root
    host: localhost
    encoding: UTF8
    port: 5454

production:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev